# Generated by Django 2.1.5 on 2019-04-09 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190407_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 14, 56, 12, 977518)),
        ),
    ]
