# Generated by Django 2.1.5 on 2019-04-09 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190409_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 16, 39, 22, 859165)),
        ),
    ]
