# Generated by Django 2.1.5 on 2019-04-09 17:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20190409_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesdislikes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likesdislikes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likesdislikes',
            name='user_react',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_reaction',
        ),
        migrations.AddField(
            model_name='post',
            name='user_reaction_dislikes',
            field=models.ManyToManyField(blank=True, related_name='user_reaction_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user_reaction_likes',
            field=models.ManyToManyField(blank=True, related_name='user_reaction_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 17, 10, 40, 479237)),
        ),
        migrations.DeleteModel(
            name='LikesDislikes',
        ),
    ]
