# Generated by Django 2.1.5 on 2019-04-07 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190406_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 7, 12, 41, 25, 492662, tzinfo=utc), null=True),
        ),
    ]
