# Generated by Django 2.1.5 on 2019-04-07 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190407_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 4, 7, 15, 49, 0, 461460, tzinfo=utc), null=True),
        ),
    ]
