# Generated by Django 2.1.5 on 2019-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190407_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birthday',
            field=models.CharField(max_length=25),
        ),
    ]
